# Generated by Django 2.1.2 on 2018-10-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20181030_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
