# Generated by Django 2.1.2 on 2018-10-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20181030_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='user',
            new_name='userName',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='id',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(help_text='Enter Branch Name.', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
