# Generated by Django 2.1 on 2018-10-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_auto_20181031_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='password1',
            field=models.CharField(default='admin', max_length=15),
        ),
        migrations.AddField(
            model_name='students',
            name='user_name',
            field=models.CharField(default='admin', max_length=15, unique=True),
        ),
    ]
